bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               .classpath,\
               src/,\
               build.properties,\
               icons/,\
               lib/
source.. = src/,\
           src/main/resources/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               lib/